# Libraries

In [14]:
import numpy as np
import pandas as pd

# Data

In [55]:
filenames = ["data/ugz_ogd_air_d1_2023.csv", "data/ugz_ogd_air_d1_2024.csv"]

dfs = [
    pd.read_csv(file).assign(year=int(file[-8:-4])).drop(columns=["Status", "Intervall"])
    for file in filenames
]

df_all = pd.concat(dfs, ignore_index=True)

In [54]:
df_all_pivot = df_all.pivot(index=["Datum", "Standort"], columns="Parameter", values="Wert")
df_all_pivot.drop(columns=["CO", "O3_max_h1", "O3_nb_h1>120", "SO2", "PN"])

df_all_pivot.tail()

Parameter                                        CO     NO    NO2    NOx  \
Datum                 Standort
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse  0.36   9.24  34.43  25.41
2024-12-31T00:00+0100 Zch_Heubeeribüel          NaN   5.07  28.53  18.98
                      Zch_Rosengartenstrasse    NaN  21.20  40.10  37.96
                      Zch_Schimmelstrasse       NaN  18.14  38.21  34.53
                      Zch_Stampfenbachstrasse  0.39   8.81  35.57  25.66

Parameter                                         O3  O3_max_h1  O3_nb_h1>120  \
Datum                 Standort
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse   6.90      14.23           0.0
2024-12-31T00:00+0100 Zch_Heubeeribüel         13.42      27.65           0.0
                      Zch_Rosengartenstrasse    5.97      14.60           0.0
                      Zch_Schimmelstrasse       7.71      17.00           0.0
                      Zch_Stampfenbachstrasse   7.55      18.73           0.0

Parameter                                       PM10  PM2.5        PN   SO2
Datum                 Standort
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse  16.72  14.94   6279.76  1.01
2024-12-31T00:00+0100 Zch_Heubeeribüel         13.75  13.36       NaN   NaN
                      Zch_Rosengartenstrasse   21.54  21.01       NaN   NaN
                      Zch_Schimmelstrasse      18.54  18.57  10485.44   NaN
                      Zch_Stampfenbachstrasse  19.18  17.44   9102.82  1.06

In [53]:
param_units = (
    df_all[["Parameter", "Einheit"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

param_units

       Parameter Einheit
0            SO2   µg/m3
1             CO   mg/m3
2            NOx     ppb
3             NO   µg/m3
4            NO2   µg/m3
5             O3   µg/m3
6           PM10   µg/m3
7          PM2.5   µg/m3
8      O3_max_h1   µg/m3
9   O3_nb_h1>120       1
10            PN   1/cm3