# Libraries

In [4]:
import numpy as np
import pandas as pd

# Data

## Air Pollution Data

In [9]:
def read_files(file_paths: list, drop_columns: list):
    dfs = [
        pd.read_csv(file).assign(year=int(file[-8:-4])).drop(columns=drop_columns)
        for file in file_paths
    ]

    df = pd.concat(dfs, ignore_index=True)

    return df

In [10]:
filenames_pollutants = ["data/ugz_ogd_air_d1_2023.csv", "data/ugz_ogd_air_d1_2024.csv"]

df_pollutants = read_files(file_paths=filenames_pollutants, drop_columns=["Status", "Intervall"])

In [11]:
param_units_pollutants = (
    df_pollutants[["Parameter", "Einheit"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

param_units_pollutants

       Parameter Einheit
0            SO2   µg/m3
1             CO   mg/m3
2            NOx     ppb
3             NO   µg/m3
4            NO2   µg/m3
5             O3   µg/m3
6           PM10   µg/m3
7          PM2.5   µg/m3
8      O3_max_h1   µg/m3
9   O3_nb_h1>120       1
10            PN   1/cm3

In [12]:
df_pollutants_pivot = df_pollutants.pivot(index=["Datum", "Standort"], columns="Parameter", values="Wert")
df_pollutants_pivot = df_pollutants_pivot.drop(columns=["CO", "O3_max_h1", "O3_nb_h1>120", "SO2", "PN"])

df_pollutants_pivot.tail()

Parameter                                         NO    NO2    NOx     O3  \
Datum                 Standort
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse   9.24  34.43  25.41   6.90
2024-12-31T00:00+0100 Zch_Heubeeribüel          5.07  28.53  18.98  13.42
                      Zch_Rosengartenstrasse   21.20  40.10  37.96   5.97
                      Zch_Schimmelstrasse      18.14  38.21  34.53   7.71
                      Zch_Stampfenbachstrasse   8.81  35.57  25.66   7.55

Parameter                                       PM10  PM2.5
Datum                 Standort
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse  16.72  14.94
2024-12-31T00:00+0100 Zch_Heubeeribüel         13.75  13.36
                      Zch_Rosengartenstrasse   21.54  21.01
                      Zch_Schimmelstrasse      18.54  18.57
                      Zch_Stampfenbachstrasse  19.18  17.44

## Traffic Data

In [29]:
df_traffic = pd.read_csv("data/traffic_data_2023_2024.csv")

In [30]:
df_traffic.head()

,ZSName,MessungDatZeit,AnzFahrzeuge,year,pollutant_station
0,Rosengartenstrasse (Nordstrasse),2023-01-01T00:00:00,688.0,2023,Zch_Rosengartenstrasse
1,Rosengartenstrasse (Nordstrasse),2023-01-01T01:00:00,1370.0,2023,Zch_Rosengartenstrasse
2,Rosengartenstrasse (Nordstrasse),2023-01-01T02:00:00,1041.0,2023,Zch_Rosengartenstrasse
3,Rosengartenstrasse (Nordstrasse),2023-01-01T03:00:00,661.0,2023,Zch_Rosengartenstrasse
4,Rosengartenstrasse (Nordstrasse),2023-01-01T04:00:00,528.0,2023,Zch_Rosengartenstrasse