# Libraries

In [14]:
import numpy as np
import pandas as pd

# Data

In [56]:
filenames = ["data/ugz_ogd_air_d1_2023.csv", "data/ugz_ogd_air_d1_2024.csv"]

dfs = [
    pd.read_csv(file).assign(year=int(file[-8:-4])).drop(columns=["Status", "Intervall"])
    for file in filenames
]

df_all = pd.concat(dfs, ignore_index=True)

In [58]:
df_all_pivot = df_all.pivot(index=["Datum", "Standort"], columns="Parameter", values="Wert")
df_all_pivot = df_all_pivot.drop(columns=["CO", "O3_max_h1", "O3_nb_h1>120", "SO2", "PN"])

df_all_pivot.tail()

Parameter                                         NO    NO2    NOx     O3  \
Datum                 Standort
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse   9.24  34.43  25.41   6.90
2024-12-31T00:00+0100 Zch_Heubeeribüel          5.07  28.53  18.98  13.42
                      Zch_Rosengartenstrasse   21.20  40.10  37.96   5.97
                      Zch_Schimmelstrasse      18.14  38.21  34.53   7.71
                      Zch_Stampfenbachstrasse   8.81  35.57  25.66   7.55

Parameter                                       PM10  PM2.5
Datum                 Standort
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse  16.72  14.94
2024-12-31T00:00+0100 Zch_Heubeeribüel         13.75  13.36
                      Zch_Rosengartenstrasse   21.54  21.01
                      Zch_Schimmelstrasse      18.54  18.57
                      Zch_Stampfenbachstrasse  19.18  17.44

In [59]:
param_units = (
    df_all[["Parameter", "Einheit"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

param_units

       Parameter Einheit
0            SO2   µg/m3
1             CO   mg/m3
2            NOx     ppb
3             NO   µg/m3
4            NO2   µg/m3
5             O3   µg/m3
6           PM10   µg/m3
7          PM2.5   µg/m3
8      O3_max_h1   µg/m3
9   O3_nb_h1>120       1
10            PN   1/cm3